description: All python packages in the tre before modularisation (Python 3.13 compatible version).
packages:
- py-aiohttp
- py-altair@5.5.0
- py-asn1crypto
- py-attrs
- py-automat
- py-backcall
- py-beautifulsoup4
- py-bitarray
- py-black
- py-bleach
- py-blinker
- py-bokeh
- py-certifi
- py-chardet
- py-click
- py-colorama
- py-configobj
- py-constantly
- py-cryptography@2.8
- py-cx-oracle@7.3.0
- py-cycler
- py-dask@2024.1.0
- py-decorator
- py-defusedxml
- py-docutils
- py-entrypoints
- py-fastapi
- py-flake8
- py-flask
- py-flask-compress
- py-google-cloud-storage
- py-gunicorn
- py-h5py
- py-hail
- py-httplib2
- py-hyperlink
- py-idna
- py-incremental
- py-ipykernel
- py-ipython
- py-ipython-genutils
- py-ipywidgets
- py-isort
- py-jedi
- py-jinja2
- py-joblib
- py-jsonpatch
- py-jsonpointer
- py-jsonschema@3.2.0
- py-jupyter
- py-jupyter-client
- py-jupyter-console
- py-jupyter-core
- py-keras
- py-keyring
- py-keyrings-alt
- py-kiwisolver
- py-markupsafe
- py-matplotlib
- py-mistune
- py-mypy
- py-mypy-extensions
- py-nbconvert
- py-nbformat
- py-netifaces
- py-nltk
- py-notebook
- py-numpy
- py-oauthlib
- py-optuna
- py-openpyxl
- py-packaging
- py-pandas
- py-pandocfilters
- py-parso
- py-pexpect
- py-pickleshare
- py-pillow
- py-polars@1.33.0
- py-prometheus-client
- py-prompt-toolkit
- py-ptyprocess
- py-pyaml
- py-pyarrow
- py-pyasn1
- py-pyasn1-modules
- py-pydantic
- py-pygments@2.4.1
- py-pyjwt
- py-pyodbc
- py-pyopenssl
- py-pyparsing
- py-pyrsistent@0.16.0
- py-pysam
- py-pyserial
- py-pytest-asyncio
- py-pytest-cov
- py-pytz
- py-pyzmq
- py-qtconsole
- py-requests
- py-requests-unixsocket
- py-scanpy@1.9.3
- py-scikit-learn
- py-scipy
- py-seaborn
- py-secretstorage
- py-send2trash
- py-setuptools
- py-shap
- py-six
- py-sqlalchemy
- py-statsmodels
- py-tensorflow
- py-terminado
- py-testpath
- py-tornado
- py-tox
- py-traitlets
- py-twisted
- py-types-requests
- py-types-setuptools
- py-tzdata@2023.3
- py-urllib3
- py-uvloop
- py-vcfpy
- py-virtualenv
- py-wcwidth
- py-webencodings
- py-widgetsnbextension
- py-xgboost
- py-xlsxwriter
- py-zope-interface
- py-popcorn
- py-tretools
- py-rpy2
- py-jupytext
- py-yhaplo
- py-autoflake
- py-brewer2mpl
- py-bump2version
- py-cloudpathlib@0.19.0
- py-flake8-docstrings
- py-ldpred
- py-matplotlib-venn
- py-myst-nb
- py-nimfa
- py-pip-tools
- py-plinkio
- py-pydeseq2
- py-pytest-cases
- py-pytest-flask
- py-pytest-httpx
- py-python-dateutil
- py-python-debian
- py-pytz-deprecation-shim@0.1.0.post0
- py-pyxdg
- py-qmplot
- py-pytest
- py-sas7bdat
- py-service-identity
- py-singledispatch
- py-tabpfn
- py-types-pyyaml
- py-vegafusion
- py-vegafusion-python-embed
- py-visidata@0.98.1
- py-visions
- py-vl-convert-python
- py-ydata-profiling
- py-ldsc
- py-pycryptodome
- py-cget
- py-datetime
- py-argparse
- py-ggplot
- py-keras
- py-statistics
executables:
- python3.13
